server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ec-site
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # 以下の設定は開発用
  thymeleaf:
    cache: false
